language: node_js
node_js:
  - 0.8
services:
  - mongodb
env:
  - yeoman_test=true
install:
  - npm install
  - npm install -g testacular@canary
  - gem install compass
before_script:
  - node app &
  - sleep 5
script:
  - npm run-script yeoman-test
  - npm run-script yeoman-build
  - npm test